[theme]
primaryColor = "#9b87f5"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
